### ISSUE TITLE
Help with definition of target sequence

### ISSUE THREAD

**Issue by cdiaz45** [tsailabSJ/changeseq#11]
Hello, thank you so much for your great tools. I am new to the guideseq, circleseq and changeseq world so I am trying to get my head around the definitions. In your manifest, you have the target sequences for all of these tools.  Specially you refer to target sequences by "Target sequence for that sample. Accepts degenerate bases." My question is, is the target sequence always the same as the guide sequence + Pam. Or does it change depending on the strand position of the on-target? Apologies for the probably very basic question. Thank you in advance, Carmen

**Comment by YichaoOU** [comment]
Yes, `target sequence always the same as the guide sequence + Pam`
